%%Definingstruct
Members=struct('Name',{},'HomeDistrict',{},'Age',{},'Course',{},'Village',{},'Tribe',{},'Religion',{},'Interest',{},'FacialRepresentation',{});
%Member1
Members(1).Name='KemigisaTasha';
Members(1).HomeDistrict='Kampala';
Members(1).Age=19;
Members(1).Course='AMI';
Members(1).Village='Kololo';
Members(1).Tribe='Mutooro';
Members(1).Religion='Christian';
Members(1).Interest='shopping';
Members(1).FacialRepresentation=imread("ngc6543a.jpg");
%Member2
Members(2).Name='AyebarePrudence';
Members(2).HomeDistrict='Mbarara';
Members(2).Age=22;
Members(2).Course='WAR';
Members(2).Village='Mbarara';
Members(2).Tribe='Munyankore';
Members(2).Religion='Christian';
Members(2).Interest='Eating';
Members(2).FacialRepresentation=imread("ngc6543a.jpg");
%member3
Members(3).Name='Kenyimoses';
Members(3).HomeDistrict='jinja';
Members(3).Age=21;
Members(3).Course='meb';
Members(3).Village='buwenda';
Members(3).Tribe='kuku';
Members(3).Religion='Christian';
Members(3).Interest='swimming';
Members(3).FacialRepresentation=imread("ngc6543a.jpg");
%member4
Members(4).Name='zzimbeenock';
Members(4).HomeDistrict='zana';
Members(4).Age=21;
Members(4).Course='war';
Members(4).Village='masaka';
Members(4).Tribe='muganda';
Members(4).Religion='Christian';
Members(4).Interest='rapping';
Members(4).FacialRepresentation=imread("ngc6543a.jpg");
%Member(5)
Members(5).Name='oketchsimon';
Members(5).HomeDistrict='jinja';
Members(5).Age=22;
Members(5).Course='ami';
Members(5).Village='kigaya';
Members(5).Tribe='musoga';
Members(5).Religion='Christian';
Members(5).Interest='football';
Members(5).FacialRepresentation=imread("ngc6543a.jpg");
%Member6
Members(6).Name='NakyagabaBabra';
Members(6).HomeDistrict='busia';
Members(6).Age=23;
Members(6).Course='ape';
Members(6).Village='buhayenji';
Members(6).Tribe='samia';
Members(6).Religion='Christian';
Members(6).Interest='watching';
Members(6).FacialRepresentation=imread("ngc6543a.jpg");
%Member7
Members(7).Name='PearlFlavia';
Members(7).HomeDistrict='kazo';
Members(7).Age=22;
Members(7).Course='war';
Members(7).Village='kashwa';
Members(7).Tribe='munyankole';
Members(7).Religion='Christian';
Members(7).Interest='playingvolleyball';
Members(7).FacialRepresentation=imread("ngc6543a.jpg");
%Member8
Members(8).Name='KagoyaAnnLauriene';
Members(8).HomeDistrict='Iganga';
Members(8).Age=21;
Members(8).Course='PTI';
Members(8).Village='Iganga';
Members(8).Tribe='MUsoga';
Members(8).Religion='Christian';
Members(8).Interest='WatchingMovies';
Members(8).FacialRepresentation=imread("ngc6543a.jpg");
%Member9
Members(9).Name='OyugiAndrewLinus';
Members(9).HomeDistrict='Kaberamaido';
Members(9).Age=23;
Members(9).Course='WAR';
Members(9).Village='Okile';
Members(9).Tribe='Kumam';
Members(9).Religion='Christian';
Members(9).Interest='WatchingMovies';
Members(9).FacialRepresentation=imread("ngc6543a.jpg");
%Member10
Members(10).Name='OmaliEmmanuel';
Members(10).HomeDistrict= 'Tororo';
Members(10).Age=23;
Members(10).Course='WAR';
Members(10).Village='Mukuju';
Members(10).Tribe='Etesot';
Members(10).Religion='Catholic';
Members(10).Interest='football';
Members(10).FacialRepresentation=imread("ngc6543a.jpg");
